config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :arifacts
  resources :tenants do
    resources :projects do
    	get 'users', on: :member
    	put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arifact.rb
class Arifact < ApplicationRecord
	attr_accessor :upload
  belongs_to :project

  MAX_FILE_SIZE 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  validate :uploaded_file_size

  private

  	def upload_to_s3
  		
  	end

  	def uploaded_file_size
  		if upload
  			errors.add(:upload, "File size must be less than #{self.class::MAX_FILE_SIZE}") unless upload.size <= self.class::MAX_FILE_SIZE
  		end
  	end
end

app/controllers/arifacts_controller.rb
class ArifactsController < ApplicationController
  before_action :set_arifact, only: [:show, :edit, :update, :destroy]

  # GET /arifacts
  # GET /arifacts.json
  def index
    @arifacts = Arifact.all
  end

  # GET /arifacts/1
  # GET /arifacts/1.json
  def show
  end

  # GET /arifacts/new
  def new
    @arifact = Arifact.new
  end

  # GET /arifacts/1/edit
  def edit
  end

  # POST /arifacts
  # POST /arifacts.json
  def create
    @arifact = Arifact.new(arifact_params)

    respond_to do |format|
      if @arifact.save
        format.html { redirect_to @arifact, notice: 'Arifact was successfully created.' }
        format.json { render :show, status: :created, location: @arifact }
      else
        format.html { render :new }
        format.json { render json: @arifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arifacts/1
  # PATCH/PUT /arifacts/1.json
  def update
    respond_to do |format|
      if @arifact.update(arifact_params)
        format.html { redirect_to @arifact, notice: 'Arifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @arifact }
      else
        format.html { render :edit }
        format.json { render json: @arifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arifacts/1
  # DELETE /arifacts/1.json
  def destroy
    @arifact.destroy
    respond_to do |format|
      format.html { redirect_to arifacts_url, notice: 'Arifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arifact
      @arifact = Arifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arifact_params
      params.require(:arifact).permit(:name, :key, :project_id)
    end
end

app/helpers/arifacts_helper.rb
module ArifactsHelper
end

app/views/arifacts/_form.html.erb
<%= form_with(model: arifact, local: true) do |form| %>
  <% if arifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arifact.errors.count, "error") %> prohibited this arifact from being saved:</h2>

      <ul>
      <% arifact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :arifact_name %>
  </div>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key, id: :arifact_key %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :arifact_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arifacts/edit.html.erb
<h1>Editing Arifact</h1>

<%= render 'form', arifact: @arifact %>

<%= link_to 'Show', @arifact %> |
<%= link_to 'Back', arifacts_path %>

app/views/arifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arifacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arifacts.each do |arifact| %>
      <tr>
        <td><%= arifact.name %></td>
        <td><%= arifact.key %></td>
        <td><%= arifact.project %></td>
        <td><%= link_to 'Show', arifact %></td>
        <td><%= link_to 'Edit', edit_arifact_path(arifact) %></td>
        <td><%= link_to 'Destroy', arifact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arifact', new_arifact_path %>

app/views/arifacts/new.html.erb
<h1>New Arifact</h1>

<%= render 'form', arifact: @arifact %>

<%= link_to 'Back', arifacts_path %>

app/views/arifacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @arifact.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @arifact.key %>
</p>

<p>
  <strong>Project:</strong>
  <%= @arifact.project %>
</p>

<%= link_to 'Edit', edit_arifact_path(@arifact) %> |
<%= link_to 'Back', arifacts_path %>